# Generated by Django 5.2.4 on 2025-07-10 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="member",
            name="debt",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="issue_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
